# Neural Turing Machine - Associative Recall Task Results
### * Before running this notebook you'll need to train the NTM on the copy task.
This notebook evaluates the NTM trained on an associative recall task. T

In [1]:
import numpy as np
import tensorflow as tf
from src.tf.ntm import NTM

tf.config.set_visible_devices([], 'GPU')

In [2]:
ntm = NTM(external_output_size=18)

### Create a test input

In [3]:
length = np.random.randint(2, 7)
seq = [np.random.randint(2, size=(6, 3)) for _ in range(length)]
seq.append(np.ones(shape=(6, 3)) * -1)
print(seq)

[array([[1, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 1]]), array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0]]), array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])]


### Load weights of the trained NTM model.

In [4]:
ntm.load_weights('assoc_model/weights')

### Reset the NTMs memory and feed it the test input

In [5]:
state = ntm.get_start_state()

for item in seq:
    _, state = ntm(tf.convert_to_tensor(item, dtype='float32'), state)

query_i = np.random.randint(len(seq) - 2)
query = seq[query_i]
y_true = seq[query_i + 1]

pred, _ = ntm(query, state)
pred = tf.nn.sigmoid(tf.reshape(pred, shape=(6, 3))).numpy()
pred = np.round(pred).astype('int32')
print(y_true)
print(pred)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 0]
 [1 0 0]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 0]
 [1 0 0]]
